#!/usr/bin/env bash
# Creates a file and traps some signals
echo $$ >> /var/run/myscript.pid

trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' 15
trap 'echo "Y U no love me?!"' 2
trap 'sudo rm -f /var/run/myscript.pid; exit' 3

while :
do echo "To infinity and beyond"
sleep 2
done
