#!/usr/bin/env bash
# Parse an apache log file to see the IP addresses visiting a website and the different status codes returned to each request by the server
# The output is then piped into a command that processes the results by grouping the IP addresses and the status codes they received
# A final command is then used to sort and print the data

logfile="apache-access.log"
awk -F ' ' '{print $1 " " $9}' $logfile | awk '{nums[$1" "$2]++}END{for (num in nums) print nums[num], num}' | sort -k1 -n -r
