#!/usr/bin/env bash
# Alters the '/etc/hosts' file
sudo cp /etc/hosts ~/hosts.new
sed -i.bak 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i "$ a 8.8.8.8	facebook.com" ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
